### ISSUE TITLE
DTS Sound Unbound

### ISSUE THREAD

**Issue by Slava848** [Slava848/improved-train#1]
DTS Sound Unbound https://apps.microsoft.com/store/detail/dts-sound-unbound/9PJ0NKL8MCSJ?referrer=appbadge&source=apps.microsoft.com

**Comment by Slava848** [comment]
> DTS Sound Unbound https://apps.microsoft.com/store/detail/dts-sound-unbound/9PJ0NKL8MCSJ?referrer=appbadge&source=apps.microsoft.com

> - [x] - []()

**Comment by Macolc27** [comment]
Io non aggiusto gli errori in continuazione  ho anche una mia vita
